// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWcPsWM8oy3LW42f6ICBCqEDe_e4St6eQ',
    appId: '1:483950661092:web:16ac153462e0df533b8bf1',
    messagingSenderId: '483950661092',
    projectId: 'pulsebeat-f48c9',
    authDomain: 'pulsebeat-f48c9.firebaseapp.com',
    storageBucket: 'pulsebeat-f48c9.firebasestorage.app',
    measurementId: 'G-MNL735CDPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVuhzguThsHCGJufBit1hBWfCBASFc-w',
    appId: '1:483950661092:android:125207711aeaacbd3b8bf1',
    messagingSenderId: '483950661092',
    projectId: 'pulsebeat-f48c9',
    storageBucket: 'pulsebeat-f48c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBZPd73WC0MHg_0siXRmhLGEMU0V-ppGw',
    appId: '1:483950661092:ios:1bf887778c88d8173b8bf1',
    messagingSenderId: '483950661092',
    projectId: 'pulsebeat-f48c9',
    storageBucket: 'pulsebeat-f48c9.firebasestorage.app',
    iosBundleId: 'com.example.testing3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBZPd73WC0MHg_0siXRmhLGEMU0V-ppGw',
    appId: '1:483950661092:ios:1bf887778c88d8173b8bf1',
    messagingSenderId: '483950661092',
    projectId: 'pulsebeat-f48c9',
    storageBucket: 'pulsebeat-f48c9.firebasestorage.app',
    iosBundleId: 'com.example.testing3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWcPsWM8oy3LW42f6ICBCqEDe_e4St6eQ',
    appId: '1:483950661092:web:e483762df7d8f7673b8bf1',
    messagingSenderId: '483950661092',
    projectId: 'pulsebeat-f48c9',
    authDomain: 'pulsebeat-f48c9.firebaseapp.com',
    storageBucket: 'pulsebeat-f48c9.firebasestorage.app',
    measurementId: 'G-KBZKSXRJQL',
  );
}
